### ISSUE TITLE
[Bug] RadioButton: Only tappable on text and radio button (not the whole width) + non-adaptive width

### ISSUE THREAD

**Issue by LouisBorleeAdevinta** [adevinta/spark-ios#1075]
Here's the difference between the Checkbox and the RadioButton

https://github.com/user-attachments/assets/48ea4cfa-1cc2-4b8d-ad28-50f3609bac46

**Comment by LouisBorleeAdevinta** [comment]
After fix 

https://github.com/user-attachments/assets/ec0b0d94-6a2d-41bd-a9c6-1014faff90e8

**Comment by LouisBorleeAdevinta** [comment]
Branch 1075-bug-radiobutton

**Comment by elisa-hery** [comment]
@LouisBorleeAdevinta 

Tested on iPhone SE & iPad pro.

I found only 1 issue : if I want to change theme, it crashes (is it linked to the trick we did so I'll be able to test ?)

![Image](https://github.com/user-attachments/assets/801e5d79-0670-48d8-b449-4ad587cc8ebb)

another remark : this improvement does not work on horizontal layout but that was not asked by the customer and that does not seem useful 

Otherwise everything is ok. I tested various combinations with : 
- long label 
- many items
- disabled state
- space containers 
- with label on the left
- the biggest/smallest dynamic type
- with screen rotation

**Comment by elisa-hery** [comment]
About the theme issue, we created another task --> https://github.com/orgs/adevinta/projects/4?pane=issue&itemId=72061222 

So this ticket is validated ✅  @LouisBorleeAdevinta
