### ISSUE TITLE
[Component] Tabs SwiftUI.

### ISSUE THREAD

**Issue by michael-zimmermann** [adevinta/spark-ios#347]
Linked to Issue https://github.com/adevinta/spark-ios/issues/234
Create a SwiftUI implementation of the tab

**Comment by elisa-hery** [comment]
@turolopezsanabria it's ok for me ✅ 

If you want to check, here is a video of tabs / swift UI ⬇  
https://github.com/adevinta/spark-ios/assets/142396647/d3eb624a-407e-4762-a0be-ecee4e93cd5c

**Comment by JeremiasUX** [comment]
Looks good to me

**Comment by elisa-hery** [comment]
I just noticed a bug that wasn't here before 😅 
```
When I click on a tab, 
Then this tab can either be pressed state, or selected state, randomly. 
```

This bug concerns : 

- [ ] UI kit
- [x] swift UI

Seen with @michael-zimmermann , it could be caused through rebases (because the branch was opened for so long). @JeremiasUX @turolopezsanabria FYI I'm putting back this ticket to `in progress`.

https://github.com/adevinta/spark-ios/assets/142396647/b635c133-de49-48fa-a59f-f4a01c8a0dbb

**Comment by michael-zimmermann** [comment]
The PR has been merged.
Please test on `main`

**Comment by elisa-hery** [comment]
Previous bug is fixed ✅ 
We noticed another small bug on tabs swift UI, that will be fixed in another ticket --> https://github.com/adevinta/spark-ios/issues/509
So I'm closing this ticket @michael-zimmermann
