### ISSUE TITLE
[Component] Button

### ISSUE THREAD

**Issue by thomas-leguellec** [adevinta/spark-ios#367]

**Comment by elisa-hery** [comment]
Test branch : `refacto/button/all`

**Comment by robergro** [comment]
* **surface button does not match [the specs](https://www.figma.com/file/NsGfE3UnbhEyAPpVf3B60P/Spark-Components?type=design&node-id=1%3A53&mode=design&t=TmPcc14h45K13Nt5-1) when disabled. Is it because of the grey background ?**
Yes, if I remove the background on the demo app when the intent is surface, the color is now good (see below)

![Image](https://github.com/adevinta/spark-ios/assets/6044208/9bc92289-ca02-4036-bec9-a98f47092549)

* **I think you told me it was the normal behaviour but I just wanted to check : when I switch from normal state (image&text) to highlighted state (with only text), is it okay that image is still there ?**
Yes, because the current state has no value (selected, disabled, …), it takes always the default value (the normal state)

* **why is there a blank space on the right of the component ?**
Because…. No sorry it is a mistake !

* **same question as for UI kit, when there is too much text in the button, what happens ? I tried to simulate it with dynamic types, here is the result ⬇️ is design team ok with that ?**
We don’t have other option, if the available space is not big enough, the text is truncated …  It is the same thing for all component with a static height

**Comment by elisa-hery** [comment]
Ok, ready for design review ✅ 
new branch is : `refacto/button/fix`

**Comment by elisa-hery** [comment]
Approved by @JeremiasUX ✅  (see slack thread [here](https://adevinta.slack.com/archives/C04UNBTD7FF/p1706264513581949)). I'm moving it to RFP !
