### ISSUE TITLE
[Component] RadioButton: Add Intents of new design.

### ISSUE THREAD

**Issue by michael-zimmermann** [adevinta/spark-ios#449]
- Add the new intents and remove the old states.
- Deprecate header and labels, these will be covered by a generic FormField component.

**Comment by elisa-hery** [comment]
@michael-zimmermann is it for swift UI or UI kit ?

**Comment by michael-zimmermann** [comment]
@elisa-hery this is for both the UIKit component and the UIKit component.
I've added new demos for the new component which is aligned to the other components.
I left the old version of the demo for the radio button for regression purposes. These are marked as Deprecated in the demo app.

**Comment by elisa-hery** [comment]
@michael-zimmermann a few comments : 
1) (UI kit) when I rotate the screen (or update the accessibility size, or switch to dark mode) **the space between group label and the first radio button disappears**
2) (UI kit) when i **uncheck trailing label _and_ vertical layout**, the behavior of the component is weird



https://github.com/adevinta/spark-ios/assets/142396647/94178343-50f6-4348-93ef-920a10852959


**3) (UI kit and Swift UI) about horizontal layout** : if content is too big for the screen, it doesn't become scrollable and label is squeezed. Therefore, for big font sizes, the horizontal layout is not adapted. There's nothing about that in the specs but it can be an accessibility problem.


<img src="https://github.com/adevinta/spark-ios/assets/142396647/fc041a54-4376-41e5-9c02-de75546b0729" alt="isolated" width="200"/>


**4) (UI kit) about containers** : for horizontal layout, if I add all space containers, and then remove them, the radio buttons group does not fit to the space, it remains squeezed

https://github.com/adevinta/spark-ios/assets/142396647/47edcb9d-278a-4c74-a338-ac9c32296d2c


 **5) the animation is different between UI kit and swift UI** : on swift UI we can see the "pressed" state by a simple click on radio button. On UIKit, we need to stay pressed, a simple click does not trigger the pressed state. That's why the result is quite different between both components. Is it normal ?
 
UI kit : 


https://github.com/adevinta/spark-ios/assets/142396647/f65ff981-d871-493e-9896-d735c5e80285



Swift UI : 



https://github.com/adevinta/spark-ios/assets/142396647/fd41d6ee-d6a0-4032-b044-15d4effe9c4a

**Comment by michael-zimmermann** [comment]
- The animation. I've created a follow-up ticked: https://github.com/orgs/adevinta/projects/4?pane=issue&itemId=43990206
- The problem with the horizontal layout if it doesn't fit. We had discussed this briefly with UX and at the time, the consensus was to  ignore it for now If the user abuses the component, then we will maybe fix it. The user has the possibility to add the component to a scroll view and handle horizontal scrolling. But I wouldn't see this as part of the component.

**Comment by elisa-hery** [comment]
Hey @michael-zimmermann so if I sum up:
1. checked, this is fixed ✅ 
2. not fixed ❌ we ignore these 3 problems related to horizontal layouts
3. not fixed ❌ we ignore these 3 problems related to horizontal layouts
4.  not fixed ❌ we ignore these 3 problems related to horizontal layouts
5. will be handled in [github.com/orgs/adevinta/projects/4?pane=issue&itemId=43990206](https://github.com/orgs/adevinta/projects/4?pane=issue&itemId=43990206) 

So if design review is ok, go for merging ✅
