### ISSUE TITLE
[Component] Icon button

### ISSUE THREAD

**Issue by thomas-leguellec** [adevinta/spark-ios#520]

**Comment by elisa-hery** [comment]
Test branch : `refacto/button/all`

**Comment by elisa-hery** [comment]
Result of the tests : 
- about **small size** : according to the specs, touch area should be 44px and it's not. 


https://github.com/adevinta/spark-ios/assets/142396647/46b17c20-d6b5-44a2-9b4e-57a2a8ed3178


- Also, i'm not sure if we should have small square iconButtons (but it's no big deal)



<img src="https://github.com/adevinta/spark-ios/assets/142396647/eb89f0ed-ddd1-45e2-abb3-028e482efb02" alt="isolated" width="200"/>





- accessibility : voice over canot read this button even when it's enabled, I think it's a problem


https://github.com/adevinta/spark-ios/assets/142396647/2bd023c5-f917-47d4-abcb-eb707b713c40




- please note that functionality is hard to test because demo app is not so close from real behavior of iconButton. It would be great to have a beta-tester Polaris team, to see how it works in real conditions

**Comment by elisa-hery** [comment]
@robergro my comments : 
- same question about surface / disabled : 
<img width="123" alt="Capture d’écran 2024-01-19 à 16 38 43" src="https://github.com/adevinta/spark-ios/assets/142396647/2d6acd3b-9873-440f-a710-189986ae9bf9">

- same question about the margin on the right : 
<img width="183" alt="Capture d’écran 2024-01-19 à 16 41 07" src="https://github.com/adevinta/spark-ios/assets/142396647/cc7db761-795a-4a5c-8476-87775a079a0a">

- we have this a11y problem that we won't be able to fix now, but I think we have to think about it : "arrow" will be read by voiceover so it's not understandable for non english speakers.
<img width="464" alt="Capture d’écran 2024-01-19 à 16 43 22" src="https://github.com/adevinta/spark-ios/assets/142396647/b1a0da1a-6259-4d8c-a42a-851c2236382a">

**Comment by robergro** [comment]
* **same question about surface / disabled :**
I copy/past my answer from the another ticket :
*Yes, if I remove the background on the demo app when the intent is surface, the color is now good (see below)*

* **same question about the margin on the right:**
I copy/past my answer from the another ticket :
Because…. No sorry it is a mistake !

* **we have this a11y problem that we won't be able to fix now, but I think we have to think about it : "arrow" will be read by voiceover so it's not understandable for non english speakers.**
We cannot provide a default text value for the accessibility for the icon, but the consumer can set manually a value if he wants !
I read this (blog)[https://medium.com/capital-one-tech/building-accessible-ios-apps-827c3469a3e9] and he says:
*Icons generally should be marked as accessibilityHidden as they don’t add any additional meaning. The text they are next to should add all the context needed.*

**Comment by elisa-hery** [comment]
Ok, ready for design review ✅ 
new branch is : `refacto/button/fix`
