### ISSUE TITLE
[Button] Refactoring

### ISSUE THREAD

**Issue by robergro** [adevinta/spark-ios#557]
- [x] Rename Text to title to have same property as a native UIButton ([PR](https://github.com/adevinta/spark-ios/pull/573))
- [x] Inherite from UIControl and not UIView ([PR](https://github.com/adevinta/spark-ios/pull/579))
- [x] Add title and attributedTitle for state (get and set func) ([PR](https://github.com/adevinta/spark-ios/pull/579))
- [x] Split the Button to have a IconButton ([PR](https://github.com/adevinta/spark-ios/pull/701))
- [x] Update snapshot testing ([PR](https://github.com/adevinta/spark-ios/pull/701))
- [ ] Update Wiki

**Comment by elisa-hery** [comment]
Test branch : `refacto/button/all`

**Comment by elisa-hery** [comment]
ℹ️ what changed ?
- now the content can be updated according to the state (eg : a content for default state, a different one for selected state)
- we now have a `isSelected` state

**Comment by elisa-hery** [comment]
@robergro here are my 2 questions : 
- question : what happens if a text is too big for the button ? Is there an ellipsis in the middle of the text, like for a large dynamic types ? We need to check if design is ok with that
<img width="179" alt="Capture d’écran 2024-01-19 à 15 23 57" src="https://github.com/adevinta/spark-ios/assets/142396647/46aebc6a-159a-4394-9ac5-b78cd23cbd3d"> 
<br/><br/>  
- a11y : contrary to iconButton, voice over recognize the component but does not identify it as a button, and I think it's not normal. `Traits` should not be defined as "static text", WDYT ? 
<br/><br/>

<img width="540" alt="Capture d’écran 2024-01-19 à 15 28 27" src="https://github.com/adevinta/spark-ios/assets/142396647/5411f9fa-4cab-4881-a3d5-529ffd3d61c9">

**Comment by elisa-hery** [comment]
@robergro questions about iconButton  : 
- about **small size** : according to the specs, touch area should be 44px and it's not. 


https://github.com/adevinta/spark-ios/assets/142396647/46b17c20-d6b5-44a2-9b4e-57a2a8ed3178


- Also, i'm not sure if we should have small square iconButtons (but it's no big deal)



<img src="https://github.com/adevinta/spark-ios/assets/142396647/eb89f0ed-ddd1-45e2-abb3-028e482efb02" alt="isolated" width="200"/>





- accessibility : voice over canot read this button even when it's enabled, I think it's a problem


https://github.com/adevinta/spark-ios/assets/142396647/2bd023c5-f917-47d4-abcb-eb707b713c40




- please note that functionality is hard to test because demo app is not so close from real behavior of iconButton. It would be great to have a beta-tester Polaris team, to see how it works in real conditions

**Comment by robergro** [comment]
* **question : what happens if a text is too big for the button ? Is there an ellipsis in the middle of the text, like for a large dynamic types ? We need to check if design is ok with that**
We don’t have other option, if the available space is not big enough, the text is truncated …  It is the same thing for all component with a static height

* **a11y : contrary to iconButton, voice over recognize the component but does not identify it as a button, and I think it's not normal. `Traits` should not be defined as "static text", WDYT ?**
I fixed it, the consumer need to set a property to have the expected content when voice over is enabled. On the demo I setted a value ("My icon button")

* **about small size : according to the specs, touch area should be 44px and it's not.**
The size is 32px and on iOS, it is a very bad practice to update the size of the tapeable area (here ton 44px), we already informed all the team about this choice/decision. 

* **Also, i'm not sure if we should have small square iconButtons (but it's no big deal)**
Agree with that, but I think we can change this rule later, the UI/UX should just be careful if they really want to use this size…

* **accessibility : voice over canot read this button even when it's enabled, I think it's a problem**
You’re right. It should be ok now ! I added a property on the demo app to switch between the default value and the value which can be set by the consumer (if he want to have an another value)

* **please note that functionality is hard to test because demo app is not so close from real behavior of iconButton. It would be great to have a beta-tester Polaris team, to see how it works in real conditions**
Yes you’re right ! But I don’t really know we can test that before create the beta of Polaris (Friday to Monday before publish to the AppStore)
And maybe we can hide the configuration with a button to simplify your test, wdytat ?

**Comment by elisa-hery** [comment]
- A11y is now fixed
<img width="366" alt="Capture d’écran 2024-01-26 à 11 47 53" src="https://github.com/adevinta/spark-ios/assets/142396647/d8b3c73e-992c-4e19-93b8-31996a814829">

- the rest is ok ✅ 

**--> ready for design review !**

**Comment by elisa-hery** [comment]
Approved by @JeremiasUX ✅  (see slack thread [here](https://adevinta.slack.com/archives/C04UNBTD7FF/p1706264513581949)). I'm moving it to RFP !
