### ISSUE TITLE
[Tag] Add AttributedText

### ISSUE THREAD

**Issue by robergro** [adevinta/spark-ios#839]
Currently, the consumer can only set a text on the Tag.
We need to add the possibility to have an AttributedText.

**Comment by elisa-hery** [comment]
branch : `tag/text`

What to test : 
- swift UI & UI kit
- try the transition from attributed text (AT) to classic text
- dynamic types
- tablets 
- intents / variants are not impacted 

Result @robergro  : a few bugs were found **on UI kit only** :  
1. because of a default on demo app, we cannot check that the AT are well cropped if too long. We'll release it anyway because it's urgent but we have to fix this issue. [The dedicated ticket](https://github.com/adevinta/spark/issues/1938) is in the backlog.
2. for a tag with AT, if I switch the theme, the intent or the variant, the AT lost its color / typo 

https://github.com/adevinta/spark-ios/assets/142396647/8a04e27c-c3c0-4c8b-8a5c-33264236065a


 Is it normal ? 

3. when I update dynamic types, attributed text's size does not update

**Comment by robergro** [comment]
The point number is fixed now on the review
