### ISSUE TITLE
[Component] Radio-button: wrong radio-button size

### ISSUE THREAD

**Issue by thomas-leguellec** [adevinta/spark-ios#853]

**Comment by thomas-leguellec** [comment]
![Image](https://github.com/adevinta/spark-ios/assets/123980564/a4189154-44e6-47b3-9619-9639d26fec3f)

Polaris ticket: https://jira.ets.mpi-internal.com/browse/PT-271

**Comment by aycil-alican** [comment]
Test branch: component/853_radio_button_bug
To test checkbox and radio button together; You can check this screen on demo project.

![Image](https://github.com/adevinta/spark-ios/assets/139964419/f795bab3-8755-4916-b541-c2f795125b8b)

**Comment by elisa-hery** [comment]
result of the test : 
- we found another problem between checkboxes and radio button (this bug was already here before the fix) --> here is [the ticket](https://github.com/orgs/adevinta/projects/4/views/10?pane=issue&itemId=57367277) 
- apart from that, screenshots of UI kit and swift UI seems ok  ⬇  BUT i'd like to test with label on the left, since [the bug on Polaris](https://jira.ets.mpi-internal.com/browse/PT-271) occured with label on the left, do you think it would be possible @aycil-alican  ? 


<img src="https://github.com/adevinta/spark-ios/assets/142396647/d6f010d4-7492-401a-8512-3f917f500e65" alt="isolated" width="300"/>

<img src="https://github.com/adevinta/spark-ios/assets/142396647/911dce56-2419-4505-b7ce-9fb9953c1bb0" alt="isolated" width="300"/>

**Comment by elisa-hery** [comment]
on iPhone 15 / iOS version 17.0, with the label on the left, I have this issue :

<img src="https://github.com/adevinta/spark-ios/assets/142396647/55886707-f521-4e7a-869c-f9a65282a4ff" alt="isolated" width="200"/>

In the same conditions but with iOS 17.2 @aycil-alican does **not** have the issue.
It's probably related to the implementation on demo app, but with Alican we agreed that it should be checked with iOS team.

PS : If this is resolved while I'm in vacations, don't hesitate to merge this ticket.

**Comment by aycil-alican** [comment]
Hello, I also checked this issue on same similator but still haven't faced with it. I talk with ohter team members and we can skip this for now.
https://github.com/adevinta/spark-ios/assets/139964419/8d729d4c-fbdb-42ed-bda1-c3c6799e2ac0
