### ISSUE TITLE
[Bug] TextFieldAddons UIKit: Addons x position not refreshed on border width change

### ISSUE THREAD

**Issue by LouisBorleeAdevinta** [adevinta/spark-ios#999]
Here is a before and after

![Image](https://github.com/adevinta/spark-ios/assets/124776620/22b196fc-89c8-46a2-8893-ae14c49597a7)
![Image](https://github.com/adevinta/spark-ios/assets/124776620/4a4801d0-232c-4737-ab28-5f6bb9115f0b)

**Comment by elisa-hery** [comment]
ℹ the bug was reported here --> https://adevinta.slack.com/archives/C04QCSQGQUX/p1718615936805859

**Comment by elisa-hery** [comment]
Ok the bug is fixed and I didn't find any regression ✅  (checked on tablet / iPhone 15 / with all different kind of add-ons / different a11y sizes)

**before** (you can see the white space on both size of add-ons): 

![Image](https://github.com/adevinta/spark-ios/assets/142396647/05168baf-237e-4afb-8ce8-37e9a40fa3e0)

**after** : 
![Image](https://github.com/adevinta/spark-ios/assets/142396647/83bcddbb-0ef1-483d-a03e-68ea72c8b02d)
